# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlockHookLear' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking', '~> 3.0'
  # Pods for BlockHookLear

  target 'BlockHookLearTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlockHookLearUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
